<a href="https://colab.research.google.com/github/Nicko-o/0_PyTorch_Learning/blob/main/00_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


## Intro To Tensors

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get Tensor back as Python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[5, 6, 7], [8, 9, 10]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 5,  6,  7],
         [ 8,  9, 10]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([2, 2, 3])

In [15]:
TENSOR[0][0][0]

tensor(1)

### Random Tensors

Random tensors are important because the way many neural networks learn is that they start with tensors full of random number and then adjust those random numbers to better represent the data.

```Start with random numbers -> look at data -> update random numers -> look at data -> update random numbers```

In [16]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4725, 0.5924, 0.6407, 0.7432],
        [0.6871, 0.2097, 0.1920, 0.7777],
        [0.1136, 0.1993, 0.1208, 0.3854]])

In [17]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [18]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
ones.dtype

torch.float32

In [21]:
zeros.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [22]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Notes:** The three big errors with PyTorch. & Deep Learning:
1. Tensors not right datatype
2. Tensor not right shape
3. Tensor not on the right device

In [24]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None, # Make sure tensors are on the same device when operating on them both together
                               requires_grad=False)
float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [25]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [26]:
test_tensor = float_16_tensor*float_32_tensor
test_tensor, test_tensor.dtype

(tensor([ 9., 36., 81.]), torch.float32)

### Getting information from tensors

1. get dtype from tensor
2. get shape from tensor
3. use tensor.device to make sure it's on the correct device

In [27]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.9969, 0.9298, 0.5266, 0.9533],
        [0.5922, 0.4925, 0.6755, 0.5189],
        [0.4362, 0.5995, 0.9513, 0.1210]])

In [28]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.9969, 0.9298, 0.5266, 0.9533],
        [0.5922, 0.4925, 0.6755, 0.5189],
        [0.4362, 0.5995, 0.9513, 0.1210]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [29]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
print(tensor + 10)
print(torch.add(tensor, 10))

tensor([11, 12, 13])
tensor([11, 12, 13])


In [30]:
# Multiply tensor by 10
print(tensor*10)

# Try out PyTorch in-built functions
print(torch.mul(tensor, 10))

tensor([10, 20, 30])
tensor([10, 20, 30])


In [31]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

In [32]:
# Element wise. multiplcation
print(tensor * tensor)


tensor([1, 4, 9])


In [33]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [34]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [35]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 613 µs, sys: 0 ns, total: 613 µs
Wall time: 630 µs


In [36]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 54 µs, sys: 10 µs, total: 64 µs
Wall time: 67.2 µs


tensor(14)

### One of the most common errors are shape errors. So make sure the inner dimensions match!! x\*y & y\*z

In [37]:
result = torch.matmul(torch.rand(25, 5), torch.rand(5, 82))
result.shape

torch.Size([25, 82])

In [38]:
# Shapes for matrix multiplication - 'matmul' = 'mm'
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_B = torch.tensor([[7,8],
                        [9,10],
                        [11, 12]])

# To fix shape issues, manipulate the shape of one of the tensors by using transpose
tensor_B = tensor_B.T

print(f"Transposed tensor B: {tensor_B}\n")
print(torch.matmul(tensor_A, tensor_B))
print(torch.mm(tensor_A, tensor_B))

Transposed tensor B: tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])
tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])


## Finding the min, max, mean, sum etc (tensor aggregation)

In [39]:
# Create a tensor
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [40]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [41]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [42]:
# Find the mean - note: Requires float, int64 doesn't work
torch.mean(x.type(torch.float64))

tensor(46., dtype=torch.float64)

In [43]:
# Find the sum
torch.sum(x)

tensor(460)

## Find the positional min and max

In [44]:
x.argmin(), x[0]

(tensor(0), tensor(1))

In [45]:
x.argmax(), x[9]

(tensor(9), tensor(91))

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all '1' dimension from a tensor
* Unsqueeze - add a '1' dimension to a target tensor
* Permute - Return a view of the input with dimension permuted (swapped) in a certain way

In [46]:
# Create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape, x.dtype

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), torch.float32)

In [47]:
# Add an extra dimension
x_reshaped = x.reshape(3, 3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [48]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [49]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [50]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [51]:
# torch.squeeze() - removes all single dimensions from a target tensor
z, z.shape, z.squeeze(), z.squeeze().shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([1, 9]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]))

In [52]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim
z_squeezed = z.squeeze()
z_unsqueezed = z_squeezed.unsqueeze(dim=0)
z_squeezed, z_squeezed.shape, z_unsqueezed, z_unsqueezed.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]),
 tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([1, 9]))

In [53]:
test_var = z_unsqueezed.unsqueeze(dim=2)
test_var, test_var.shape

(tensor([[[5.],
          [2.],
          [3.],
          [4.],
          [5.],
          [6.],
          [7.],
          [8.],
          [9.]]]),
 torch.Size([1, 9, 1]))

In [54]:
# torch.permute - rearranges the dimensions in specific order, the returned tensor is a view!
x_original = torch.rand(size=(244, 244, 3))

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1)

print(x_original.shape, x_permuted.shape)
print("Remember, it's a view so they still share the same place in a memory!")


torch.Size([244, 244, 3]) torch.Size([3, 244, 244])
Remember, it's a view so they still share the same place in a memory!


In [55]:
# Proof that is is a view:
print(f"Old value: {x_permuted[0, 0, 0]}")
x_original[0, 0, 0] = 666
print(f"New Value: {x_permuted[0, 0, 0]}")

Old value: 0.7889020442962646
New Value: 666.0


## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [56]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [57]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [58]:
# index on middle bracket
print(x[0, 0])
print("Is the same as")
print(x[0][0])

tensor([1, 2, 3])
Is the same as
tensor([1, 2, 3])


In [59]:
# index on the most inner bracket (last dimension)
x[0][2][1]

tensor(8)

In [60]:
# You can also use ":" to select "all" of a target dimnesion
x[:, :, 1]

tensor([[2, 5, 8]])

In [61]:
print(x[0, 1, :])
print("Is the same as:")
print(x[0, 1])

tensor([4, 5, 6])
Is the same as:
tensor([4, 5, 6])


In [62]:
# Return 9
print(x[0, 2, 2])

# Return 3, 6, 9
print(x[0, :, 2])

tensor(9)
tensor([3, 6, 9])


## PyTorch tensors & NumPy

NumPy is a numberical computing library.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [63]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [64]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float32)

In [65]:
# Change the. value of array
array = array + 1
array, tensor # They do not share the memory

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [66]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [67]:
# Change the tensor
tensor = tensor + 1
tensor, numpy_tensor # They don't share memory

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducability (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [68]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.3724, 0.7779, 0.9354, 0.3518],
        [0.5534, 0.2457, 0.3789, 0.8929],
        [0.4739, 0.1793, 0.9419, 0.5740]])
tensor([[0.0438, 0.1187, 0.3796, 0.9320],
        [0.5899, 0.7314, 0.7256, 0.7147],
        [0.2978, 0.5660, 0.1981, 0.1151]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [69]:
# Let's make some random but reproducible tensors
import torch
# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch object on the GPUs (and making faster computation)

GPUs + faster computation on numbers

In [3]:
# !nvidia-smi

### 2. Check for GPU access with PyTorch

In [2]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [4]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device


'cuda'

In [5]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU to achieve faster operations.

In [6]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [7]:
# Move tensor to GPU
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [10]:
# If tensor is on GPU, can't transform it to NumPy
# First transform it back to CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [11]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')